from pathlib import Path
import json
import os
import re
import shutil
from profiles import candidate_cards, render_profiles

ROOT=Path(__file__).parent
DIST=ROOT/'docs'
DIST.mkdir(exist_ok=True)
shutil.copytree(ROOT/'static',DIST,dirs_exist_ok=True)
def head(title,description):
 return f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#102b3a"><meta name="description" content="{description}"><title>{title} · Arquivo Político</title><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/profile.css"><script defer src="/app.js"></script></head><body><a class="skip" href="#conteudo">Pular para o conteúdo</a><div class="topline"><div class="wrap"><span>MEMÓRIA POLÍTICA BRASILEIRA</span><span><span class="status-dot"></span>EDIÇÃO 001 <span class="hide-small">/ DESDE A VIRADA DO MILÊNIO</span></span></div></div><header class="header"><nav class="wrap nav" aria-label="Navegação principal"><a href="/" class="brand" aria-label="Arquivo Político, início"><span class="brand-mark" aria-hidden="true">a</span><span>arquivo<small>político</small></span></a><button class="menu-button" aria-controls="main-nav" aria-expanded="false">Menu +</button><div class="navlinks" id="main-nav"><a href="/#contexto">O ponto de partida</a><a href="/#eleicoes">Eleições</a><a href="/#metodo">Nosso método</a><a class="navcta" href="/eleicoes/2002/">Explorar 2002 <span aria-hidden="true">↗</span></a></div></nav></header><main id="conteudo">'''
footer='''</main><footer><div class="wrap footer-inner"><a href="/" class="footer-brand">arquivo político<span>_</span></a><p>Memória para entender. Evidências para avaliar.<br>Projeto independente em construção · Edição inicial / 2002</p></div></footer></body></html>'''

sources=[
 ('ibge','IBGE · Censo Demográfico 2000: população e domicílios','https://www.ibge.gov.br/estatisticas/sociais/saude/9663-censo-demografico-2000.html?edicao=9771'),
 ('real','Banco Central · História do Plano Real','https://www.bcb.gov.br/controleinflacao/planoreal'),
 ('bc2001','Banco Central · Relatório anual de 2001: contexto econômico e racionamento','https://www.bcb.gov.br/pec/boletim/banual2001/rel2001introdp.pdf'),
 ('bc2002','Banco Central · Ata do Copom de dezembro de 2002: câmbio e inflação','https://bcb.gov.br/publicacoes/atascopom/18122002'),
 ('tse','TSE · Candidaturas, votação e resultados de 2002','https://www.tse.jus.br/eleicoes/eleicoes-anteriores/eleicoes-2002/candidaturas-votacao-e-resultados'),
 ('datas','TSE · Resolução 20.997/2002: datas e regras da eleição','https://www.tse.jus.br/legislacao/compilada/res/2002/resolucao-no-20-997-de-26-de-fevereiro-de-2002'),
 ('nomes','TSE · Diário da Justiça: nomes, partidos e números dos candidatos de 2002','https://sintse.tse.jus.br/documentos/2002/Set/6/diario-da-justica-secao-1/resolucao-no-21-170-de-6-de-agosto-de-2002-consulta-partido-politico-esclarecimentos-sistemas-inform'),
 ('lula','Câmara dos Deputados · Perfil de Lula e vitória em 2002','https://www.camara.leg.br/noticias/91015-veja-o-perfil-de-lula-o-presidente-reeleito-do-brasil/'),
 ('serra','Câmara dos Deputados · José Serra: atuação no governo FHC e disputa de 2002','https://www.camara.leg.br/tv/206227-confira-o-perfil-biografico-dos-dois-candidatos-a-presidencia-da-republica/')
]
def ref(n):return f'<a class="source-ref" href="#fonte-{sources[n-1][0]}" aria-label="Consultar fonte {n}">[{n}]</a>'
def source_section():
 return '<section class="wrap sources" id="fontes"><details open><summary>Fontes abertas. Informação verificável. <span aria-hidden="true">↗</span></summary><p>Referências desta edição. As fontes das fichas individuais também aparecem dentro de cada ficha. Consulta editorial: 5 de outubro de 2026.</p><ol>'+''.join(f'<li id="fonte-{id}"><a href="{url}" target="_blank" rel="noopener noreferrer">{label} ↗</a></li>' for id,label,url in sources)+'</ol></details></section>'

art='''<div class="hero-art"><div class="art-frame"><span class="art-stamp">BRASÍLIA / PODER & MEMÓRIA</span><svg viewBox="0 0 540 440" role="img" aria-labelledby="congress-title" xmlns="http://www.w3.org/2000/svg"><title id="congress-title">Ilustração geométrica do Congresso Nacional, com duas torres e cúpulas sobre um fundo verde</title><defs><pattern id="grid" width="22" height="22" patternUnits="userSpaceOnUse"><path d="M22 0H0V22" fill="none" stroke="#426553" stroke-opacity=".12" stroke-width=".7"/></pattern><pattern id="windows" width="8" height="9" patternUnits="userSpaceOnUse"><path d="M0 0H8M0 0V9" stroke="#b2cbb9" stroke-opacity=".7" stroke-width=".6"/></pattern><pattern id="dots" width="4" height="4" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".65" fill="#173c36" opacity=".25"/></pattern></defs><rect width="540" height="440" fill="#dce7df"/><rect width="540" height="440" fill="url(#grid)"/><circle cx="348" cy="164" r="117" fill="#d3f77d"/><circle cx="348" cy="164" r="131" stroke="#6d8b62" stroke-width=".8" fill="none" stroke-dasharray="2 5"/><path d="M0 326L540 267V440H0Z" fill="#9bb6a2"/><path d="M0 356L540 300V440H0Z" fill="url(#dots)"/><path d="M0 386L540 331M0 410L540 347M67 440L271 319M284 440L364 309M502 440L457 299" stroke="#416855" stroke-width=".7"/><path d="M64 317L421 282 499 308 139 351Z" fill="#517968"/><path d="M64 317V332L139 368V351M139 351L499 308V323L139 368" fill="#244e45"/><path d="M82 306L412 274 472 296 142 336Z" fill="#eaf0e3"/><path d="M222 116L251 112V292L222 295Z" fill="#f1f3db"/><path d="M251 112L263 119V289L251 292Z" fill="#557a67"/><path d="M222 116L251 112V292L222 295Z" fill="url(#windows)"/><path d="M269 107L298 103V287L269 290Z" fill="#f1f3db"/><path d="M298 103L310 110V284L298 287Z" fill="#557a67"/><path d="M269 107L298 103V287L269 290Z" fill="url(#windows)"/><path d="M251 186L269 184V195L251 197Z" fill="#e9eddb"/><path d="M100 300Q134 234 182 292Z" fill="#f2f3e0"/><path d="M100 300Q143 312 182 292Q148 300 100 300Z" fill="#466e5e"/><path d="M337 269Q378 329 430 260Z" fill="#f0f3df"/><ellipse cx="383.5" cy="264.5" rx="47" ry="8" transform="rotate(-6 383 264)" fill="#254e43"/><path d="M70 312L471 291" stroke="#173b33" stroke-width="1"/><path d="M37 69H90M37 69V115M503 354H463M503 354V313" stroke="#557964" fill="none"/><text x="33" y="252" transform="rotate(-90 33 252)" font-family="monospace" font-size="9" letter-spacing="2" fill="#315849">15°47′ S 47°52′ W</text><text x="383" y="91" font-family="monospace" font-size="10" fill="#315849">[ BR / 001 ]</text></svg><div class="art-caption"><span>CONGRESSO NACIONAL</span><span>ILUSTRAÇÃO EDITORIAL / BR</span></div></div><div class="art-note">O voto é um momento.<br>A trajetória é uma história.</div></div>'''

home=head('A história por trás do voto','Conheça o contexto das eleições brasileiras e a trajetória dos candidatos. Comece pela eleição de 2002, com fontes abertas e verificáveis.')
home+=f'''<section class="wrap hero"><div><div class="eyebrow">O passado também está na urna</div><h1>Antes de escolher,<br>conheça a<br><em>história inteira.</em></h1><p>Ideias, trajetórias e decisões. Explore a política brasileira para além da campanha — com contexto e fontes que você pode conferir.</p><div class="hero-actions"><a class="button" href="#eleicoes">Explorar as eleições <span aria-hidden="true">↓</span></a><a class="text-link" href="#contexto">Comece pelo contexto</a></div><div class="hero-foot"><span>FONTES À VISTA</span><span>CONTEXTO ANTES DO JULGAMENTO</span></div></div>{art}</section><div class="wrap trust-strip"><span class="label">NOSSO PONTO DE PARTIDA</span><span>TSE</span><span>IBGE</span><span>BANCO CENTRAL</span><span>CÂMARA DOS DEPUTADOS</span></div>
<section class="wrap context-section" id="contexto"><div class="section-heading"><div class="eyebrow">00 / O ponto de partida</div><h2>Um novo milênio.<br>Um país em transição.</h2><p>Para entender uma escolha, primeiro é preciso conhecer o país que foi às urnas.</p></div><div class="context-copy"><p>O Brasil entrou nos anos 2000 sob a presidência de Fernando Henrique Cardoso, após a estabilização monetária iniciada com o <strong>Plano Real, em 1994</strong>. O Censo de 2000 retratou um país com quase <strong>170 milhões de habitantes</strong>, dos quais cerca de 81% viviam em áreas urbanas.{ref(2)}{ref(1)}{ref(9)}</p><p>A virada também trouxe dificuldades. Em 2001, o <strong>racionamento de energia</strong> e um cenário internacional adverso afetaram a economia. Em 2002, a desvalorização cambial e a pressão sobre os preços compunham o ambiente da sucessão presidencial.{ref(3)}{ref(4)}</p><p>É a partir desse contexto que nosso arquivo começa: quem se apresentou para governar, de onde vinha e como sua trajetória pode ser examinada.</p><div class="context-facts"><div class="fact"><strong>169,8 mi</strong><span>HABITANTES EM 2000 {ref(1)}</span></div><div class="fact"><strong>2001</strong><span>RACIONAMENTO DE ENERGIA {ref(3)}</span></div><div class="fact"><strong>2002</strong><span>PRIMEIRO CAPÍTULO</span></div></div></div></section>
<section class="elections" id="eleicoes"><div class="wrap"><div class="section-top"><div><div class="eyebrow">01 / Escolha um capítulo</div><h2>Cada eleição tem uma história.</h2></div><p>Entre no contexto de cada época.<br>Conheça quem esteve na disputa.</p></div><nav class="year-nav" aria-label="Anos eleitorais">'''
for year in range(2002,2027,4): home+=f'<a href="#ano-{year}" class="{"current" if year==2002 else ""}">{year}</a>'
home+='''</nav><a href="/eleicoes/2002/" class="year-banner featured" id="ano-2002"><div class="year">2002</div><div><span class="badge">Capítulo disponível</span><h3>Uma nova etapa no Planalto.</h3><p>O contexto da sucessão de FHC e os seis candidatos que disputaram a Presidência.</p></div><span class="arrow" aria-hidden="true">↗</span></a>'''
for year in range(2006,2027,4):
 home+=f'''<article class="year-banner upcoming" id="ano-{year}"><div class="year">{year}</div><div><span class="badge">Próximo capítulo</span><h3>Eleições presidenciais de {year}</h3><p>Contexto, candidatos e trajetórias. Conteúdo ainda não publicado.</p></div><span class="upcoming-label">EM BREVE</span></article>'''
home+='''</div></section><section class="wrap method" id="metodo"><div class="section-heading"><div class="eyebrow">02 / Nosso compromisso</div><h2>A informação vem<br>com o caminho<br>até a fonte.</h2><p>Você merece saber de onde veio uma afirmação — e o que ainda falta apurar.</p></div><div class="method-list"><div class="method-item"><span class="num">[01]</span><div><h3>Contexto faz parte do fato.</h3><p>Uma fala, uma decisão ou um indicador precisam de data, circunstância e responsabilidade identificada.</p></div></div><div class="method-item"><span class="num">[02]</span><div><h3>O mesmo critério para todos.</h3><p>Fontes identificadas e distinção entre promessa, execução e resultado. Sem nota geral ou recomendação de voto.</p></div></div><div class="method-item"><span class="num">[03]</span><div><h3>Transparência sobre o que sabemos.</h3><p>Esta edição reúne as seis trajetórias de 2002, com propostas, atuação nos cargos e acontecimentos posteriores. As fontes, os desfechos documentados e os limites de cada pesquisa estão nas páginas individuais.</p></div></div></div></section>'''
home+=source_section()+footer
(DIST/'index.html').write_text(home)

election=head('Eleições 2002','O contexto da eleição presidencial de 2002, seus seis candidatos e referências para conhecer a história da disputa.')
election+=f'''<div class="wrap breadcrumb"><a href="/">Início</a><span>/</span><a href="/#eleicoes">Eleições</a><span>/</span><span aria-current="page">2002</span></div><section class="wrap election-hero"><div><div class="eyebrow">Capítulo 01 / Eleições presidenciais</div><h1>2002. O Brasil<br>escolhe um novo<br>caminho.</h1><p>Seis candidatos, uma sucessão e um país diante de desafios econômicos. Conheça o cenário da eleição que levou Lula à Presidência.</p><a class="button" href="#candidatos">Conhecer os candidatos <span aria-hidden="true">↓</span></a></div><div class="year-poster"><div class="poster-meta"><span>ARQUIVO ELEITORAL</span><span>BR / 01</span></div><div class="big">2002<span style="font-size:45px;letter-spacing:0">_</span></div><div class="poster-meta"><span>06 OUT · 1º TURNO</span><span>27 OUT · 2º TURNO</span></div></div></section><div class="wrap election-meta"><div><span>PRIMEIRO TURNO</span><strong>6 de outubro {ref(6)}</strong></div><div><span>SEGUNDO TURNO</span><strong>27 de outubro {ref(6)}</strong></div><div><span>CANDIDATURAS</span><strong>6 nomes na disputa {ref(7)}</strong></div><div><span>CARGO</span><strong>Presidente da República</strong></div></div>
<section class="wrap election-context" id="contexto-2002"><div class="section-heading"><div class="eyebrow">O cenário antes do voto</div><h2>O que estava<br>em jogo?</h2><p>Estabilidade econômica, sucessão presidencial e as alternativas apresentadas ao eleitor.</p></div><div class="event-line"><article class="event"><span class="date">1994 → 2000 / ANTECEDENTES</span><h3>O país depois do Plano Real</h3><p>A estabilização monetária iniciada em 1994 era um marco da década anterior. A eleição de 2002 ocorreria ao final do governo FHC, de cuja equipe José Serra havia participado como ministro.{ref(2)}{ref(9)}</p></article><article class="event"><span class="date">2001 / ECONOMIA E INFRAESTRUTURA</span><h3>O racionamento entrou na rotina</h3><p>A crise de energia e o ambiente externo desfavorável afetaram a atividade econômica. O relatório do Banco Central identifica também a crise argentina e a desaceleração internacional entre os choques daquele ano.{ref(3)}</p></article><article class="event"><span class="date">2002 / A SUCESSÃO</span><h3>Pressão econômica e disputa política</h3><p>A desvalorização do real pressionou os preços durante 2002. Seis candidatos disputaram a Presidência; Lula, do PT, e José Serra, do PSDB, chegaram ao segundo turno.{ref(4)}{ref(7)}{ref(9)}</p></article></div></section>
<section class="candidates-section" id="candidatos"><div class="wrap"><div class="section-top"><div><div class="eyebrow">Os nomes daquela eleição</div><h2>Quem queria governar o Brasil?</h2></div><p style="font-size:13px;color:var(--muted);max-width:280px">Partidos e números são de 2002. Retratos de acervo, não necessariamente daquela campanha.</p></div><div class="candidate-controls"><label class="search-field"><span aria-hidden="true">⌕</span><input id="candidate-search" type="search" placeholder="Buscar por nome ou partido" aria-label="Buscar candidato por nome ou partido"></label><span class="sort-note" id="candidate-count" aria-live="polite">6 candidatos encontrados</span></div><div class="candidates-grid">{candidate_cards(ROOT)}</div><p class="scope-note">As fotografias têm seus créditos indicados abaixo de cada imagem e são exibidas com enquadramento adaptado ao layout. As imagens de Zé Maria e Rui Costa Pimenta mantêm as licenças vinculadas nos créditos. Abra uma trajetória para consultar a linha do tempo, as ideias, a atuação política, as propostas e os acontecimentos posteriores documentados. Ausência de informação nesta edição não significa ausência de fatos. Nomes e partidos: TSE.{ref(7)}</p></div></section>
<section class="wrap result"><div class="section-heading"><div class="eyebrow">O desfecho da disputa</div><h2>Das urnas<br>ao próximo capítulo.</h2><p>A eleição é um marco da trajetória. A avaliação do mandato exige acompanhar o que veio depois.</p></div><div class="result-box"><span class="pill">RESULTADO / SEGUNDO TURNO</span><h3 class="winner">Lula foi eleito presidente.</h3><p>Luiz Inácio Lula da Silva venceu José Serra no segundo turno de 2002. Seu primeiro mandato presidencial começou em 2003.{ref(8)}{ref(9)}</p><a href="https://www.tse.jus.br/eleicoes/eleicoes-anteriores/eleicoes-2002/candidaturas-votacao-e-resultados" target="_blank" rel="noopener noreferrer">Consultar o arquivo de resultados do TSE ↗</a></div></section><div class="wrap"><a class="backlink" href="/#eleicoes">← <span>Voltar ao arquivo de eleições</span></a></div>'''
election+=source_section()
election+=footer
(DIST/'eleicoes/2002').mkdir(parents=True,exist_ok=True)
(DIST/'eleicoes/2002/index.html').write_text(election)
(DIST/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="8" fill="#102b3a"/><text x="16" y="46" font-family="monospace" font-size="46" fill="#f5f5ee">a</text><path d="M19 53h27" stroke="#d3f77d" stroke-width="4"/></svg>')
render_profiles(ROOT, head, footer, output_dir=DIST)

(DIST/"profile.css").write_text((ROOT/"profile.css").read_text())

# A project on GitHub Pages is served under the repository name.
base = os.environ.get('BASE_PATH', '/arquivo-politico').strip('/')
if base:
    for page in DIST.rglob('*.html'):
        text = re.sub(r'(href|src)="/(?!/)', lambda m: m.group(1)+'="/'+base+'/', page.read_text())
        page.write_text(text)
(DIST/'.nojekyll').touch()
print('Static site ready in docs/. Base path: /'+base)
